# TO MAKE FIGURE 4 FROM KOEHN ET AL. 2021
# takes/loads forage fish model runs generated by Run_ForageFishmodel_Siple_etal_2019.R
# for forage fish projections for sardine and anchovy
# then runs the seabird model for both the reference run (No fishing on forage fish)
# then seabird model with low constant fishing and moderate constant fishing
# for both the restricted seabird and flexible seabird (two seabird life histories)
#Plots
# median relative abundance (seabird model with fishing compared to no fishing) across simulations
# and probability of extinction (% runs that drop below 10% of mean median seabird biomass w/out fishing) across simulations 
# and finally, variance in results across simulations. 
setwd(here::here())


# Loop through both forage fish and generate seabird runs
foragefish =c("Anchovy", "Sardine")
for(i in 1:length(foragefish)) {
  fishuse = foragefish[i]
  load(file=paste(fishuse,1,"nofish",".RData",sep="_"))
  source(file.path("Run_seabird_2lifehistory.R"))
  load(file=paste(fishuse,2,"constF",".RData",sep="_"))
  load(file=paste(fishuse,3,"constFhi",".RData",sep="_"))
  #fish = constF$penguinfood
  
  # LOW CONSTANT FISHING and flexible and restrict seabird
  fish = constF$avgbiomass
  # constant low, C1, constant Hi, C2, C3
  
  
  # 1
  # FIND STABLE DISTRIBUTION
  maxage_use = maxage[1]
  testinits = rep(10000, length = (maxage_use + 1))
  K_init = sum(testinits[2:(maxage_use+1)])
  
  
  stable_dis = SeabirdPop_dd_nofish_nostoch(Nyear = Nyear, inits = testinits, juv_s = year1sur, adult_s = adultsur, agebreeding = agebreeding[1], 
                                            K = K_init, 
                                            maxage = maxage[1], egg_s = eggsur, chick_s = chicksur, clutch = clutch[1])
  
  total = sum(stable_dis$pop[2,1:(maxage_use+1),Nyear+1])
  stable_dis$pop[2,1:(maxage_use+1),Nyear+1]/total
  #plot(colSums(stable_dis$pop[2,1:(maxage_use+1),]), ylim = c(0,450000))
  stable = stable_dis$pop[2,1:(maxage_use+1),Nyear+1]/total
  
  sum(stable[2:(maxage_use+1)])
  testinits = stable*(1000000) # hypothetical starting population
  #K = sum(testinits[2:(maxage_use+1)])
  K = 1000000
  
  seabirdoutB = list(breeders = matrix(nrow = nsims, ncol = Nyear), # at end of year
                     recruits = matrix(nrow = nsims, ncol = Nyear),
                     totalpop = matrix(nrow = nsims, ncol = Nyear),
                     fledglings = matrix(nrow = nsims, ncol = Nyear),
                     eggs = matrix(nrow = nsims, ncol = Nyear),
                     testing = matrix(nrow = nsims, ncol = Nyear),
                     testing2 = matrix(nrow = nsims, ncol = Nyear),
                     testing3 = matrix(nrow = nsims, ncol = Nyear))
  
  ffbiomass = array(NA, c(2,Nyear+1,nsims))
  ffbiomass_non = array(NA, c(2,Nyear+1,nsims))
  
  #B0initB = B0init
  #B02initB = B02init
  #P0noninitB = P0noninit
  
  set.seed(216)
  for(ss in 1:nsims) {
    #firsthalf = fish[1,,ss] 
    #secondhalf = fish[2,,ss]
    firsthalf = fish[ss,] 
    secondhalf = fish[ss,]
    #   firsthalfdelay = E[c(TRUE, FALSE)]
    #   secondhalfdelay = E[c(FALSE, TRUE)]
    #   
    #   fishinghalf1 = ((firsthalf*fishing2[ss])-(firsthalfdelay*fishing[ss]))
    #   fishinghalf2 = ((secondhalf*fishing2[ss])-(secondhalfdelay*fishing[ss]))
    #make fishing2 a vector of 1 if no true biomass fishing and only use fishing vector (delayed detection)
    #make fishing vector a vector of 0 if no delayed detection 
    #   
    #   ffbiomass[1,,ss] = fishinghalf1*props[1,,ss]
    #   ffbiomass[2,,ss] = fishinghalf2*props[2,,ss]
    #   ffbiomass_non[1,,ss] = fishinghalf1*nonbreedprops[1,,ss]
    #   ffbiomass_non[2,,ss] = fishinghalf2*nonbreedprops[2,,ss]
    
    ffbiomass[1,,ss] = firsthalf*props[1,,ss]
    ffbiomass[2,,ss] = secondhalf*props[2,,ss]
    ffbiomass_non[1,,ss] = firsthalf*nonbreedprops[1,,ss]
    ffbiomass_non[2,,ss] = secondhalf*nonbreedprops[2,,ss]
    
    ffbiomass_use = ffbiomass[,,ss]
    ffbiomass_non_use = ffbiomass_non[,,ss]
    
    
    #set.seed(821)
    # specialist
    seabirdB = SeabirdPop_simple_stochastic_RS(Nyear = Nyear, inits = testinits, ffbiomass = ffbiomass_use,
                                               juv_sur = juv_base_s[,,ss], adult_sur = adult_base_s[,,ss], agebreeding = agebreeding[1],
                                               K = K, maxage = maxage[1], egg_sur = egg_base_s[,ss], chick_sur = chick_base_s[,ss],
                                               clutch = clutch[1],P0 = B0init_h_mean, B0 = B0init_h_mean, P02 = B02init_h_mean, P0non = P0noninit_h_mean, 
                                               ffbio_nonbreeders = ffbiomass_non_use, scenario = 1,
                                               ffbio_init = ffbiomass[1,,ss], ffbio_init_non = ffbiomass_non[1,,ss], fscen = 1, RS_thres = 0, 
                                               param_breeders = param_breeders_special, param_fledge = param_fledge_special, 
                                               param_fledge2 = param_fledge2_special, param_adult = param_adult_special, 
                                               param_juv = param_juv_special, param_fledge3 = param_fledge3_special)
    # seabirdB = SeabirdPop_simple_stochastic_RS(Nyear = Nyear, inits = testinits, ffbiomass = ffbiomass_use,
    #                                            juv_sur = juv_base_s[,,ss], adult_sur = adult_base_s[,,ss], agebreeding = agebreeding[1],
    #                                            K = K, maxage = maxage[1], egg_sur = egg_base_s[,ss], chick_sur = chick_base_s[,ss],
    #                                            clutch = clutch[1],P0 = B0initB[ss], B0 = B0initB[ss], P02 = B02initB[ss], P0non = P0noninitB[ss],
    #                                            ffbio_nonbreeders = ffbiomass_non_use, scenario = 1,
    #                                            ffbio_init = ffbiomass[1,,ss], ffbio_init_non = ffbiomass_non[1,,ss], fscen = 1, RS_thres = 0, 
    #                                            param_breeders = param_breeders_general, param_fledge = param_fledge_general, 
    #                                            param_fledge2 = param_fledge2_general, param_adult = param_adult_general, 
    #                                            param_juv = param_juv_general, param_fledge3 = param_fledge3_general)
    seabirdoutB[["breeders"]][ss,] = colSums(seabirdB$pop[2,5:31,])
    seabirdoutB[["recruits"]][ss,] = seabirdB$recruits
    seabirdoutB[["totalpop"]][ss,] = colSums(seabirdB$pop[2,1:31,])
    seabirdoutB[["fledglings"]][ss,] = seabirdB$pop[2,1,]
    seabirdoutB[["eggs"]][ss,] = seabirdB$pop[1,1,]
    seabirdoutB[["testing"]][ss,] = seabirdB$testing
    seabirdoutB[["testing2"]][ss,] = seabirdB$testing2
    seabirdoutB[["testing3"]][ss,] = seabirdB$testing3
    
  }
  
  
  ########################## 2 ###################################
  maxage_use = maxage[2]
  testinits = rep(10000, length = (maxage_use + 1))
  K_init = sum(testinits[2:(maxage_use+1)])
  stable_dis = SeabirdPop_dd_nofish_nostoch(Nyear = Nyear, inits = testinits, juv_s = year1sur, adult_s = adultsur, 
                                            agebreeding = agebreeding[2], 
                                            K = K_init, 
                                            maxage = maxage[2], egg_s = eggsur, chick_s = chicksur, clutch = clutch[2])
  total = sum(stable_dis$pop[2,1:(maxage_use+1),Nyear+1])
  stable_dis$pop[2,1:(maxage_use+1),Nyear+1]/total
  #plot(colSums(stable_dis$pop[2,1:(maxage_use+1),]), ylim = c(0,350000))
  stable = stable_dis$pop[2,1:(maxage_use+1),Nyear+1]/total
  sum(stable[2:(maxage_use+1)])
  testinits = stable*(1000000) # hypothetical starting population
  #K = sum(testinits[2:(maxage_use+1)])
  K = 1000000
  
  seabirdoutB2 = list(breeders = matrix(nrow = nsims, ncol = Nyear), # at end of year
                      recruits = matrix(nrow = nsims, ncol = Nyear),
                      totalpop = matrix(nrow = nsims, ncol = Nyear),
                      fledglings = matrix(nrow = nsims, ncol = Nyear),
                      eggs = matrix(nrow = nsims, ncol = Nyear),
                      testing = matrix(nrow = nsims, ncol = Nyear),
                      testing2 = matrix(nrow = nsims, ncol = Nyear),
                      testing3 = matrix(nrow = nsims, ncol = Nyear))
  
  ffbiomass = array(NA, c(2,Nyear+1,nsims))
  ffbiomass_non = array(NA, c(2,Nyear+1,nsims))
  
  #B0initB2 = B0init2
  #B02initB2 = B02init2
  #P0noninitB2 = P0noninit2
  
  set.seed(216)
  for(ss in 1:nsims) {
    
    #firsthalf = fish[1,,ss] 
    #secondhalf = fish[2,,ss]
    firsthalf = fish[ss,] 
    secondhalf = fish[ss,]
    
    ffbiomass[1,,ss] = firsthalf*props_low[1,,ss]
    ffbiomass[2,,ss] = secondhalf*props_low[2,,ss]
    ffbiomass_non[1,,ss] = firsthalf*nonbreedprops_low[1,,ss]
    ffbiomass_non[2,,ss] = secondhalf*nonbreedprops_low[2,,ss]
    
    ffbiomass_use = ffbiomass[,,ss]
    ffbiomass_non_use = ffbiomass_non[,,ss]
    
    #set.seed(821)
    # generalist
    seabirdB2 = SeabirdPop_simple_stochastic_RS(Nyear = Nyear, inits = testinits, ffbiomass = ffbiomass_use,
                                                juv_sur = juv_base_s[,,ss], adult_sur = adult_base_s[,,ss], agebreeding = agebreeding[2],
                                                K = K, maxage = maxage[2], egg_sur = egg_base_s[,ss], chick_sur = chick_base_s[,ss],
                                                clutch = clutch[2], P0 = B0init_low_mean, B0 = B0init_low_mean, P02 = B02init_low_mean, P0non = P0noninit_low_mean,  
                                                ffbio_nonbreeders = ffbiomass_non_use, scenario = 1,
                                                ffbio_init = ffbiomass[1,,ss], ffbio_init_non = ffbiomass_non[1,,ss], fscen = 1, RS_thres = 0, 
                                                param_breeders = param_breeders_general, param_fledge = param_fledge_general, 
                                                param_fledge2 = param_fledge2_general, param_adult = param_adult_general, 
                                                param_juv = param_juv_general, param_fledge3 = param_fledge3_general)
    seabirdoutB2[["breeders"]][ss,] = colSums(seabirdB2$pop[2,(agebreeding[2]+1):(maxage[2]+1),])
    seabirdoutB2[["recruits"]][ss,] = seabirdB2$recruits
    seabirdoutB2[["totalpop"]][ss,] = colSums(seabirdB2$pop[2,1:(maxage[2]+1),])
    seabirdoutB2[["fledglings"]][ss,] = seabirdB2$pop[2,1,]
    seabirdoutB2[["eggs"]][ss,] = seabirdB2$pop[1,1,]
    seabirdoutB2[["testing"]][ss,] = seabirdB2$testing
    seabirdoutB2[["testing2"]][ss,] = seabirdB2$testing2
    seabirdoutB2[["testing3"]][ss,] = seabirdB2$testing3
  }
  
  #fish = constFhi$penguinfood #turn off scenario 1 polygon
  # MODERATE CONSTANT FISHING and restricted and flexible seabirds
  fish = constFhi$avgbiomass
  
  # 1
  # FIND STABLE DISTRIBUTION
  maxage_use = maxage[1]
  testinits = rep(10000, length = (maxage_use + 1))
  K_init = sum(testinits[2:(maxage_use+1)])
  
  
  stable_dis = SeabirdPop_dd_nofish_nostoch(Nyear = Nyear, inits = testinits, juv_s = year1sur, adult_s = adultsur, agebreeding = agebreeding[1], 
                                            K = K_init, 
                                            maxage = maxage[1], egg_s = eggsur, chick_s = chicksur, clutch = clutch[1])
  
  total = sum(stable_dis$pop[2,1:(maxage_use+1),Nyear+1])
  stable_dis$pop[2,1:(maxage_use+1),Nyear+1]/total
  #plot(colSums(stable_dis$pop[2,1:(maxage_use+1),]), ylim = c(0,450000))
  stable = stable_dis$pop[2,1:(maxage_use+1),Nyear+1]/total
  
  sum(stable[2:(maxage_use+1)])
  testinits = stable*(1000000) # hypothetical starting population
  #K = sum(testinits[2:(maxage_use+1)])
  K = 1000000
  
  seabirdoutD = list(breeders = matrix(nrow = nsims, ncol = Nyear), # at end of year
                     recruits = matrix(nrow = nsims, ncol = Nyear),
                     totalpop = matrix(nrow = nsims, ncol = Nyear),
                     fledglings = matrix(nrow = nsims, ncol = Nyear),
                     eggs = matrix(nrow = nsims, ncol = Nyear),
                     testing = matrix(nrow = nsims, ncol = Nyear),
                     testing2 = matrix(nrow = nsims, ncol = Nyear),
                     testing3 = matrix(nrow = nsims, ncol = Nyear))
  
  ffbiomass = array(NA, c(2,Nyear+1,nsims))
  ffbiomass_non = array(NA, c(2,Nyear+1,nsims))
  
  #B0initB = B0init
  #B02initB = B02init
  #P0noninitB = P0noninit
  
  set.seed(216)
  for(ss in 1:nsims) {
    #firsthalf = fish[1,,ss] 
    #secondhalf = fish[2,,ss]
    firsthalf = fish[ss,] 
    secondhalf = fish[ss,]
    #   firsthalfdelay = E[c(TRUE, FALSE)]
    #   secondhalfdelay = E[c(FALSE, TRUE)]
    #   
    #   fishinghalf1 = ((firsthalf*fishing2[ss])-(firsthalfdelay*fishing[ss]))
    #   fishinghalf2 = ((secondhalf*fishing2[ss])-(secondhalfdelay*fishing[ss]))
    #make fishing2 a vector of 1 if no true biomass fishing and only use fishing vector (delayed detection)
    #make fishing vector a vector of 0 if no delayed detection 
    #   
    #   ffbiomass[1,,ss] = fishinghalf1*props[1,,ss]
    #   ffbiomass[2,,ss] = fishinghalf2*props[2,,ss]
    #   ffbiomass_non[1,,ss] = fishinghalf1*nonbreedprops[1,,ss]
    #   ffbiomass_non[2,,ss] = fishinghalf2*nonbreedprops[2,,ss]
    
    ffbiomass[1,,ss] = firsthalf*props[1,,ss]
    ffbiomass[2,,ss] = secondhalf*props[2,,ss]
    ffbiomass_non[1,,ss] = firsthalf*nonbreedprops[1,,ss]
    ffbiomass_non[2,,ss] = secondhalf*nonbreedprops[2,,ss]
    
    ffbiomass_use = ffbiomass[,,ss]
    ffbiomass_non_use = ffbiomass_non[,,ss]
    
    
    #set.seed(821)
    # specialist
    seabirdD = SeabirdPop_simple_stochastic_RS(Nyear = Nyear, inits = testinits, ffbiomass = ffbiomass_use,
                                               juv_sur = juv_base_s[,,ss], adult_sur = adult_base_s[,,ss], agebreeding = agebreeding[1],
                                               K = K, maxage = maxage[1], egg_sur = egg_base_s[,ss], chick_sur = chick_base_s[,ss],
                                               clutch = clutch[1],P0 = B0init_h_mean, B0 = B0init_h_mean, P02 = B02init_h_mean, P0non = P0noninit_h_mean, 
                                               ffbio_nonbreeders = ffbiomass_non_use, scenario = 1,
                                               ffbio_init = ffbiomass[1,,ss], ffbio_init_non = ffbiomass_non[1,,ss], fscen = 1, RS_thres = 0, 
                                               param_breeders = param_breeders_special, param_fledge = param_fledge_special, 
                                               param_fledge2 = param_fledge2_special, param_adult = param_adult_special, 
                                               param_juv = param_juv_special, param_fledge3 = param_fledge3_special)
    # seabirdB = SeabirdPop_simple_stochastic_RS(Nyear = Nyear, inits = testinits, ffbiomass = ffbiomass_use,
    #                                            juv_sur = juv_base_s[,,ss], adult_sur = adult_base_s[,,ss], agebreeding = agebreeding[1],
    #                                            K = K, maxage = maxage[1], egg_sur = egg_base_s[,ss], chick_sur = chick_base_s[,ss],
    #                                            clutch = clutch[1],P0 = B0initB[ss], B0 = B0initB[ss], P02 = B02initB[ss], P0non = P0noninitB[ss],
    #                                            ffbio_nonbreeders = ffbiomass_non_use, scenario = 1,
    #                                            ffbio_init = ffbiomass[1,,ss], ffbio_init_non = ffbiomass_non[1,,ss], fscen = 1, RS_thres = 0, 
    #                                            param_breeders = param_breeders_general, param_fledge = param_fledge_general, 
    #                                            param_fledge2 = param_fledge2_general, param_adult = param_adult_general, 
    #                                            param_juv = param_juv_general, param_fledge3 = param_fledge3_general)
    seabirdoutD[["breeders"]][ss,] = colSums(seabirdD$pop[2,5:31,])
    seabirdoutD[["recruits"]][ss,] = seabirdD$recruits
    seabirdoutD[["totalpop"]][ss,] = colSums(seabirdD$pop[2,1:31,])
    seabirdoutD[["fledglings"]][ss,] = seabirdD$pop[2,1,]
    seabirdoutD[["eggs"]][ss,] = seabirdD$pop[1,1,]
    seabirdoutD[["testing"]][ss,] = seabirdD$testing
    seabirdoutD[["testing2"]][ss,] = seabirdD$testing2
    seabirdoutD[["testing3"]][ss,] = seabirdD$testing3
    
  }
  
  
  ########################## 2 ###################################
  maxage_use = maxage[2]
  testinits = rep(10000, length = (maxage_use + 1))
  K_init = sum(testinits[2:(maxage_use+1)])
  stable_dis = SeabirdPop_dd_nofish_nostoch(Nyear = Nyear, inits = testinits, juv_s = year1sur, adult_s = adultsur, 
                                            agebreeding = agebreeding[2], 
                                            K = K_init, 
                                            maxage = maxage[2], egg_s = eggsur, chick_s = chicksur, clutch = clutch[2])
  total = sum(stable_dis$pop[2,1:(maxage_use+1),Nyear+1])
  stable_dis$pop[2,1:(maxage_use+1),Nyear+1]/total
  #plot(colSums(stable_dis$pop[2,1:(maxage_use+1),]), ylim = c(0,350000))
  stable = stable_dis$pop[2,1:(maxage_use+1),Nyear+1]/total
  sum(stable[2:(maxage_use+1)])
  testinits = stable*(1000000) # hypothetical starting population
  #K = sum(testinits[2:(maxage_use+1)])
  K = 1000000
  
  seabirdoutD2 = list(breeders = matrix(nrow = nsims, ncol = Nyear), # at end of year
                      recruits = matrix(nrow = nsims, ncol = Nyear),
                      totalpop = matrix(nrow = nsims, ncol = Nyear),
                      fledglings = matrix(nrow = nsims, ncol = Nyear),
                      eggs = matrix(nrow = nsims, ncol = Nyear),
                      testing = matrix(nrow = nsims, ncol = Nyear),
                      testing2 = matrix(nrow = nsims, ncol = Nyear),
                      testing3 = matrix(nrow = nsims, ncol = Nyear))
  
  ffbiomass = array(NA, c(2,Nyear+1,nsims))
  ffbiomass_non = array(NA, c(2,Nyear+1,nsims))
  
  #B0initB2 = B0init2
  #B02initB2 = B02init2
  #P0noninitB2 = P0noninit2
  
  set.seed(216)
  for(ss in 1:nsims) {
    
    #firsthalf = fish[1,,ss] 
    #secondhalf = fish[2,,ss]
    firsthalf = fish[ss,] 
    secondhalf = fish[ss,]
    ffbiomass[1,,ss] = firsthalf*props_low[1,,ss]
    ffbiomass[2,,ss] = secondhalf*props_low[2,,ss]
    ffbiomass_non[1,,ss] = firsthalf*nonbreedprops_low[1,,ss]
    ffbiomass_non[2,,ss] = secondhalf*nonbreedprops_low[2,,ss]
    
    ffbiomass_use = ffbiomass[,,ss]
    ffbiomass_non_use = ffbiomass_non[,,ss]
    
    #set.seed(821)
    # generalist
    seabirdD2 = SeabirdPop_simple_stochastic_RS(Nyear = Nyear, inits = testinits, ffbiomass = ffbiomass_use,
                                                juv_sur = juv_base_s[,,ss], adult_sur = adult_base_s[,,ss], agebreeding = agebreeding[2],
                                                K = K, maxage = maxage[2], egg_sur = egg_base_s[,ss], chick_sur = chick_base_s[,ss],
                                                clutch = clutch[2], P0 = B0init_low_mean, B0 = B0init_low_mean, P02 = B02init_low_mean, P0non = P0noninit_low_mean,  
                                                ffbio_nonbreeders = ffbiomass_non_use, scenario = 1,
                                                ffbio_init = ffbiomass[1,,ss], ffbio_init_non = ffbiomass_non[1,,ss], fscen = 1, RS_thres = 0, 
                                                param_breeders = param_breeders_general, param_fledge = param_fledge_general, 
                                                param_fledge2 = param_fledge2_general, param_adult = param_adult_general, 
                                                param_juv = param_juv_general, param_fledge3 = param_fledge3_general)
    seabirdoutD2[["breeders"]][ss,] = colSums(seabirdD2$pop[2,(agebreeding[2]+1):(maxage[2]+1),])
    seabirdoutD2[["recruits"]][ss,] = seabirdD2$recruits
    seabirdoutD2[["totalpop"]][ss,] = colSums(seabirdD2$pop[2,1:(maxage[2]+1),])
    seabirdoutD2[["fledglings"]][ss,] = seabirdD2$pop[2,1,]
    seabirdoutD2[["eggs"]][ss,] = seabirdD2$pop[1,1,]
    seabirdoutD2[["testing"]][ss,] = seabirdD2$testing
    seabirdoutD2[["testing2"]][ss,] = seabirdD2$testing2
    seabirdoutD2[["testing3"]][ss,] = seabirdD2$testing3
  }
  
  seabirdout$totalpop[is.na(seabirdout$totalpop)] = 0
  seabirdout2$totalpop[is.na(seabirdout2$totalpop)] = 0
  seabirdoutB$totalpop[is.na(seabirdoutB$totalpop)] = 0
  seabirdoutB2$totalpop[is.na(seabirdoutB2$totalpop)] = 0
  seabirdoutD$totalpop[is.na(seabirdoutD$totalpop)] = 0
  seabirdoutD2$totalpop[is.na(seabirdoutD2$totalpop)] = 0
  
  # save runs for each forage fish
  assign(paste(tolower(fishuse),1,sep=""),  seabirdout)
  assign(paste(tolower(fishuse),2,sep=""), seabirdout2)
  assign(paste(tolower(fishuse),"B1",sep=""), seabirdoutB)
  assign(paste(tolower(fishuse),"B2",sep=""), seabirdoutB2)
  assign(paste(tolower(fishuse),"D1",sep=""), seabirdoutD)
  assign(paste(tolower(fishuse),"D2",sep=""), seabirdoutD2)
}
# NOTE WARNINGS MAY OCCUR FOR RUNS WHERE SEABIRD CRASHES - code then sets
# these runs to seabird biomass of 0


# PLOT RESULTS
library(matrixStats)

#### new 4.2020 Tim graph ####

meanB1A = rowMeans(anchovyB1$totalpop[,201:1000]/anchovy1$totalpop[,201:1000])

meanB2A = rowMeans(anchovyB2$totalpop[,201:1000]/anchovy2$totalpop[,201:1000])

meanD1A = rowMeans(anchovyD1$totalpop[,201:1000]/anchovy1$totalpop[,201:1000])

meanD2A = rowMeans(anchovyD2$totalpop[,201:1000]/anchovy2$totalpop[,201:1000])
anchovy = cbind(meanB2A,meanD2A,meanB1A,  meanD1A)

meanB1S = rowMeans(sardineB1$totalpop[,201:1000]/sardine1$totalpop[,201:1000])

meanB2S = rowMeans(sardineB2$totalpop[,201:1000]/sardine2$totalpop[,201:1000])

meanD1S = rowMeans(sardineD1$totalpop[,201:1000]/sardine1$totalpop[,201:1000])

meanD2S = rowMeans(sardineD2$totalpop[,201:1000]/sardine2$totalpop[,201:1000])

#probability of extinction of <10% un-fished
birdthres1 = median(rowMeans(anchovy1$totalpop[,201:1000]))*0.1
birdthres2 = median(rowMeans(anchovy2$totalpop[,201:1000]))*0.1 # note flexible actually has smaller population
# size even without fishing. makes sense because shorter life span. 
prob1= median((apply(anchovyB1$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres1))}))/800)
prob2 = median((apply(anchovyB2$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres2))}))/800)
prob3= median((apply(anchovyD1$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres1))}))/800)
prob4 = median((apply(anchovyD2$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres2))}))/800)

quan1 = ((apply(anchovyB1$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres1))}))/800)
quan2 = ((apply(anchovyB2$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres2))}))/800)
quan3 = ((apply(anchovyD1$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres1))}))/800)
quan4 = ((apply(anchovyD2$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres2))}))/800)


birdthres1S = median(rowMeans(sardine1$totalpop[,201:1000]))*0.1
birdthres2S= median(rowMeans(sardine2$totalpop[,201:1000]))*0.1 # note flexible actually has smaller population
# size even without fishing. makes sense because shorter life span. 
prob1S= median((apply(sardineB1$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres1S))}))/800)
prob2S = median((apply(sardineB2$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres2S))}))/800)
prob3S= median((apply(sardineD1$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres1S))}))/800)
prob4S = median((apply(sardineD2$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres2S))}))/800)


quan1S = ((apply(sardineB1$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres1S))}))/800)
quan2S = ((apply(sardineB2$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres2S))}))/800)
quan3S = ((apply(sardineD1$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres1S))}))/800)
quan4S = ((apply(sardineD2$totalpop[,201:1000], 1, function(x){ length(which(x< birdthres2S))}))/800)

par(mfrow =c (3,2))
par(xpd = NA)
par(mar = c(1,2,2,2)) #
par(oma = c(7,9,2,10)) # bottom left top right
x = c(0.98,1,1.1,1.12)
plot(x, c( NA, median(meanB2A),median(meanD2A), NA), ylim = c(0,1), xlab = "", ylab = "", main  = "Anchovy prey",
     axes = FALSE, cex = 2)
points(x, c(NA, median(meanB1A), median(meanD1A), NA), pch = 16, cex = 2)
segments(x[2], median(meanB2A), x[3], median(meanD2A) )
segments(x[2], median(meanB1A), x[3], median(meanD1A) )
text(x = 0.88, y = 0.5, "Median relative \n abundance", cex = 1.25,xpd = NA)
#Axis(side=1, at = c(1,1.1), labels=FALSE)
Axis(side=2, labels=TRUE, las = 1)


plot(x, c( NA, median(meanB2S),median(meanD2S), NA), ylim = c(0,1), xlab = "", ylab = "", main  = "Sardine prey",
     axes = FALSE, cex = 2)
points(x, c(NA, median(meanB1S), median(meanD1S), NA), pch = 16, cex = 2)
segments(x[2], median(meanB2S), x[3], median(meanD2S) )
segments(x[2], median(meanB1S), x[3], median(meanD1S) )
#text(x = 0.88, y = 0.5, "Median relative \n abundance", cex = 1.25,xpd = NA)
#Axis(side=1, at = c(1,1.1), labels=FALSE)
Axis(side=2, labels=TRUE, las = 1)
#legend(0.85,2, legend = c("Flexible seabird", "Restricted Seabird"), col = c("black", "black"), pch = c(1,16),
     #  ncol = 2, cex = 1.2, pt.cex = 2,xpd = NA)


 plot(x, c(NA, prob2,prob4, NA), ylim = c(0,1), xlab = "", ylab = "",
      axes = FALSE, cex = 2)
 points(x,c(NA, prob1, prob3,NA), pch = 16, cex = 2)
 segments(x[2], prob2, x[3], prob4 )
 segments(x[2], prob1, x[3], prob3 )
 #Axis(side=1, at = c(1,1.1), labels=FALSE)
 Axis(side=2, labels=TRUE, las = 1)
 text(x = 0.88, y = 0.5, "Prob(Extinct)", cex = 1.25,xpd = NA)
 
 legend(1.34,2.3, legend = c("Flexible seabird", "Restricted seabird"), col = c("black", "black"), pch = c(1,16),
       cex = 1.25, pt.cex = 2,xpd = NA)
 
 plot(x, c(NA, prob2S,prob4S, NA), ylim = c(0,1), xlab = "", ylab = "",
      axes = FALSE, cex = 2)
 points(x,c(NA, prob1S, prob3S,NA), pch = 16, cex = 2)
 segments(x[2], prob2S, x[3], prob4S )
 segments(x[2], prob1S, x[3], prob3S )
 #Axis(side=1, at = c(1,1.1), labels=FALSE)
 Axis(side=2, labels=TRUE, las = 1)
# text(x = 0.88, y = 0.5, "Prob(Extinct)", cex = 1.25,xpd = NA)

 plot(x, c(NA, var(meanB2A),var(meanD2A),NA), ylim = c(0,0.055), xlab = "", ylab = "",
      axes = FALSE, cex = 2)
 points(x, c(NA, var(meanB1A), var(meanD1A), NA), pch = 16, cex = 2)
 segments(x[2], var(meanB2A), x[3], var(meanD2A) )
 segments(x[2], var(meanB1A), x[3], var(meanD1A) )
 #segments(x[1], 0, x[2], 0)
 #Axis(side=1, labels=FALSE, tick = FALSE, line = TRUE)
 Axis(side=2, labels=TRUE, las = 1)
 text(x = 0.88, y = 0.025, "Variance", cex = 1.25,xpd = NA)
 
 axis(side = 1, labels = c(expression("0.25 F"["msy"]), expression("0.5 F"["msy"])),
      at = c(1.0,1.1), line = 1.5, cex.axis = 1.5, tick = FALSE)
 #mtext("Constant Fishing Rate", side =1, line = 4)

 
 plot(x, c(NA, var(meanB2S),var(meanD2S),NA), ylim = c(0,0.055), xlab = "", ylab = "",
      axes = FALSE, cex = 2)
 points(x, c(NA, var(meanB1S), var(meanD1S), NA), pch = 16, cex = 2)
 segments(x[2], var(meanB2S), x[3], var(meanD2S) )
 segments(x[2], var(meanB1S), x[3], var(meanD1S) )
 #segments(x[1], 0, x[2], 0)
 #Axis(side=1, labels=FALSE, tick = FALSE, line = TRUE)
 Axis(side=2, labels=TRUE, las = 1)
 #text(x = 0.88, y = 0.01, "Variance", cex = 1.25,xpd = NA)
 
 axis(side = 1, labels = c(expression("0.25 F"["msy"]), expression("0.5 F"["msy"])),
      at = c(1.0,1.1), line = 1.5, cex.axis = 1.5, tick = FALSE)
 text(0.94, -0.05, "Constant Fishing Rate", xpd = NA, cex = 1.5)

 
 
